# Generated by Django 2.2.1 on 2019-05-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_system', '0002_auto_20190527_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
