# Generated by Django 2.2.1 on 2019-05-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_system', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
