# Generated by Django 2.2.1 on 2019-05-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_system', '0003_auto_20190527_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='password',
        ),
    ]
