# Generated by Django 2.2.1 on 2019-05-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_system', '0003_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggestions',
            new_name='Suggestion',
        ),
    ]
