# Generated by Django 2.2.1 on 2019-05-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_system', '0004_auto_20190520_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=20)),
            ],
        ),
    ]
