# Generated by Django 2.2.1 on 2019-06-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_system', '0004_remove_userregistration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('train_no', models.CharField(max_length=5)),
                ('doj', models.DateField()),
                ('boarding_station', models.CharField(max_length=40)),
                ('destination_station', models.CharField(max_length=40)),
                ('complaint', models.TextField()),
            ],
        ),
    ]
