# Generated by Django 2.2.1 on 2019-06-04 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_system', '0005_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='email',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='mobileNumber',
        ),
        migrations.AddField(
            model_name='complaint',
            name='ticket_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
